FORMAT: 1A
HOST: localhost/

# UAS DAVID DRANALO

Polls is a simple API allowing consumers to view polls and vote in them.

## Data Barang [/uasdaviddranalo]

### List Barang [GET/uasdaviddranalo/get.php]

+ Response 200 (application/json)

        [
             {
            "DataBarang": [
                {
                    "NamaBarang": "Dompet",
                    "Id": "111",
                    "Pengirim": "Aldi",
                    "Penerima": "Mila",
                    "AlamatBarang": "jakarta"
                },
                {
                    "NamaBarang": "Dompet",
                    "Id": "123",
                    "Pengirim": "Aldi",
                    "Penerima": "Mila",
                    "AlamatBarang": "jakarta"
                },
                {
                    "NamaBarang": "Gelas",
                    "Id": "212",
                    "Pengirim": "Budi",
                    "Penerima": "Dimas",
                    "AlamatBarang": "Palembang"
                },
                {
                    "NamaBarang": "Gelas",
                    "Id": "456",
                    "Pengirim": "Budi",
                    "Penerima": "Dimas",
                    "AlamatBarang": "Palembang"
                },
                {
                    "NamaBarang": "kaca",
                    "Id": "987",
                    "Pengirim": "fidi",
                    "Penerima": "izat",
                    "AlamatBarang": "lampung"
                }
            ]
        }
        ]

### membuat barang baru [POST]

untuk menambah pekerja baru

+ Request (application/json)

        {
        "DataBarang": [
        {
            "NamaBarang": "Nama Barang",
            "Id": "ID Barang",
            "Pengirim": "Pengirim",
            "Penerima": "Penerima",
            "AlamatBarang": "Alamat Barang"
        }
        ]
        }

+ Response 201 (application/json)

    + Headers

            Location: /uas/postapi

    + Body

            {
            "Data Pekerjaan": [
            {
                "NamaBarang": "",
                "Id": "",
                "Pengirim": "",
                "Penerima": "",
                "AlamatBarang": ""
            },
            ]
            }
            
### mengubah data [PUT]

untuk mengubah data

+ Request (application/json)

        {
        "DataBarang": [
        {
            "Id": "ID Barang",
        }
        ]
        }

+ Response 201 (application/json)

    + Headers

            Location: /uas/putapi

    + Body

            {
            "DataBarang": [
            {
                "NamaBarang": "",
                "Id": "",
                "Pengirim": "",
                "Penerima": "",
                "AlamatBarang": ""
            },
            ]
            }
            
### Menghapus data pekerja [DELETE/uasdaviddranalo/delete]

untuk menghapus data

+ Request (application/json)

        {
        "DataBarang": [
        {
            "Id": "ID Barangr",
        }
        ]
        }
        
        + Response 201 (application/json)

    + Headers

            Location: /uasdaviddranalo/delete

    + Body

            {
            " Telah Terhaps "
            ]
            }