FORMAT: 1A
HOST: localhost/

# UAS

Polls is a simple API allowing consumers to view polls and vote in them.

## Data - Data Pekerja [/uas]

### Semua List Pekerja [GET/uas/get.php]

+ Response 200 (application/json)

        [
            {
    "DataBarang": [
        {
            "NamaBarang": "Dompet",
            "Id": "111",
            "Pengirim": "Aldi",
            "Penerima": "Mila",
            "AlamatBarang": "jakarta"
        },
        {
            "NamaBarang": "Dompet",
            "Id": "123",
            "Pengirim": "Aldi",
            "Penerima": "Mila",
            "AlamatBarang": "jakarta"
        },
        {
            "NamaBarang": "Gelas",
            "Id": "212",
            "Pengirim": "Budi",
            "Penerima": "Dimas",
            "AlamatBarang": "Palembang"
        },
        {
            "NamaBarang": "Gelas",
            "Id": "456",
            "Pengirim": "Budi",
            "Penerima": "Dimas",
            "AlamatBarang": "Palembang"
        },
        {
            "NamaBarang": "kaca",
            "Id": "987",
            "Pengirim": "fidi",
            "Penerima": "izat",
            "AlamatBarang": "lampung"
        }
    ]
}
        ]

### Membuat data pekerja baru [POST]

untuk menambah pekerja baru

+ Request (application/json)

        {
        "Data Pekerjaan": [
        {
            "id_pekerja": "ID pekerja",
            "nama_pekerja": "nama pekerja",
            "umur_pekerja": "umur pekerja",
            "nama_pekerjaan": "nama / pangkatan pekerjaan",
            "alamat_pekerja": "alamat pekerja"
        }
        ]
        }

+ Response 201 (application/json)

    + Headers

            Location: /uas/post

    + Body

            {
            "Data Pekerjaan": [
            {
                "id_pekerja": "",
                "nama_pekerja": "",
                "umur_pekerja": "",
                "nama_pekerjaan": "",
                "alamat_pekerja": ""
            },
            ]
            }
            
### Mengedit data pekerja [PUT]

untuk meng-edit pekerja 

+ Request (application/json)

        {
        "Data Pekerjaan": [
        {
            "id_pekerja": "ID pekerja",
        }
        ]
        }

+ Response 201 (application/json)

    + Headers

            Location: /uas/put

    + Body

            {
            "Data Pekerjaan": [
            {
                "id_pekerja": "",
                "nama_pekerja": "",
                "umur_pekerja": "",
                "nama_pekerjaan": "",
                "alamat_pekerja": ""
            },
            ]
            }
            
### Menghapus data pekerja [DELETE/uas/delete]

untuk menghapus pekerja 

+ Request (application/json)

        {
        "Data Pekerjaan": [
        {
            "id_pekerja": "ID pekerja",
        }
        ]
        }
        
        + Response 201 (application/json)

    + Headers

            Location: /uas/delete

    + Body

            {
            " berhasil terhapus "
            ]
            }